### ISSUE TITLE
[object Object] error when replying to emails

### ISSUE THREAD

**Issue by ianaa** [roostergrin/reminders-public#6]
```
Stacktrace (most recent call first):

  at captureException (../node_modules/raven-js/src/raven.js:416:1)
  at logException (services/raven.js:21:9)
  at None (components/Messages/MessagesEditor.js:170:7)

{"status":500,"statusText":"Internal Server Error","ok":false,"type":"cors","headers":{},"body":{"error":{"from":["can't be blank","is too short (minimum is 6 characters)"]}}}
```

**Comment by ianaa** [comment]
fixed on Feb 15.
